# Generated by Django 5.1.3 on 2024-11-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
